(module branchy '#%kernel

(#%provide branchy-function)

(define-values (branchy-function)
  (lambda (lst)
    ((letrec-values 
        ([(loop) 
          (lambda (lst)
            (if (null? lst)
                -1
                (let-values ([(input) (car lst)])
                  (if (< input 18)
                      (if (< input 8)
                          (if (< input 3)
                              (if (< input 1)
                                  (+ 1 (loop (cdr lst)))
                                  (if (< input 2)
                                      (loop (cdr lst))
                                      (loop (cdr lst))))
                              (if (< input 5)
                                  (if (< input 4)
                                      (+ 3 (loop (cdr lst)))
                                      (+ 5 (loop (cdr lst))))
                                  (if (< input 6)
                                      (loop (cdr lst))
                                      (if (< input 7)
                                          (loop (cdr lst))
                                          (loop (cdr lst))))))
                          (if (< input 12)
                              (if (< input 9)
                                  (loop (cdr lst))
                                  (if (< input 10)
                                      (+ 9 (loop (cdr lst)))
                                      (if (< input 11)
                                          (+ 10 (loop (cdr lst)))
                                          (loop (cdr lst)))))
                              (if (< input 14)
                                  (if (< input 13)
                                      (+ 12 (loop (cdr lst)))
                                      (+ 13.5 (loop (cdr lst))))
                                  (if (< input 15)
                                      (+ 14 (loop (cdr lst)))
                                      (if (< input 16)
                                          (+ 15 (loop (cdr lst)))
                                          (if (< input 17)
                                              (+ 15 (loop (cdr lst)))
                                              (+ 16 (loop (cdr lst)))))))))
                      (if (< input 27)
                          (if (< input 22)
                              (if (< input 19)
                                  (+ 18 (loop (cdr lst)))
                                  (if (< input 20)
                                      (+ 19 (string-length "imm") (loop (cdr lst)))
                                      (if (< input 21)
                                          (+ 20 (loop (cdr lst)))
                                          (+ 21 (loop (cdr lst))))))
                              (if (< input 24)
                                  (if (< input 23)
                                      (loop (cdr lst))
                                      (loop (cdr lst)))
                                  (if (< input 25)
                                      (+ 24 (loop (cdr lst)))
                                      (if (< input 26)
                                          (+ 25 (loop (cdr lst)))
                                          (+ 27 (loop (cdr lst)))))))
                          (if (< input 32)
                              (if (< input 29)
                                  (if (< input 28)
                                      (+ 27 (loop (cdr lst)))
                                      (+ 29 (loop (cdr lst))))
                                  (if (< input 30)
                                      (+ 1 (loop (cdr lst)))
                                      (if (< input 31)
                                          ((letrec-values (((ploop)
                                                            (lambda (len)
                                                              (if (zero? len)
                                                                  (+ 30.5 (loop (cdr lst)))
                                                                  (+ (ploop (sub1 len)))))))
                                             ploop)
                                           31)
                                          (loop (cdr lst)))))
                              (if (< input 34)
                                  (if (< input 33)
                                      (+ 32 (loop (cdr lst)))
                                      (+ 34 (loop (cdr lst))))
                                  (if (< input 35)
                                      (loop (cdr lst))
                                      (if (< input 36)
                                          (+ 35 (loop (cdr lst)))
                                          #;(let-values (((ht) (make-hasheq)))
                                              (let-values (((start) 0)
                                                           ((end) 36)
                                                           ((inc) 1))
                                                ((letrec-values (((for-loop)
                                                                  (lambda (pos)
                                                                    (if (< pos  end)
                                                                        (let-values (((j) pos))
                                                                          (let-values ((()
                                                                                        (let-values ()
                                                                                          (let-values ((()
                                                                                                        (let-values ()
                                                                                                          (let-values ()
                                                                                                            (hash-set! ht (loop (cdr lst)) (loop (cdr lst))))
                                                                                                          (values))))
                                                                                            (values)))))
                                                                            (for-loop (+ pos inc))))
                                                                        (values)))))
                                                   for-loop)
                                                 start))
                                              ht)
                                          (if (< input 37)
                                              (+ 36 (loop (cdr lst)))
                                              #;(let-values (((ht) '#hash()))
                                                  (let-values (((start) 0)
                                                               ((end) 37)
                                                               ((inc) 1))
                                                    ((letrec-values (((for-loop)
                                                                      (lambda (ht pos)
                                                                        (if (< pos end)
                                                                            (let-values (((j) pos))
                                                                              (let-values (((ht)
                                                                                            (let-values (((ht) ht))
                                                                                              (let-values (((ht) (hash-set ht (loop (cdr lst)) 'a)))
                                                                                                (values ht)))))
                                                                                (for-loop ht (+ pos inc))))
                                                                            ht))))
                                                       for-loop)
                                                     ht
                                                     start)))
                                              (let-values (((l1) (loop (cdr lst))))
                                                (+ 38 l1))))))))))))])
      loop) lst)))

)
